---

information:
  - "Stackstorm server, event-based Ops"

parameters:

  locationId:
    information:
      - "the target data centre for this deployment"
    type: locations.list
    default: AU10

  domainName:
    information:
      - "the name of the network domain to be deployed"
    type: str
    default: StackstormFox

  networkName:
    information:
      - "the name of the Ethernet VLAN to be deployed"
    type: str
    default: StackstormNetwork

  nodeName:
    information:
      - "the name of the main node to be deployed"
    type: str
    default: stackstorm01

links:
  documentation: https://github.com/DimensionDataCBUSydney/plumbery-contrib/tree/master/fittings/devops/stackstorm

defaults:

  cloud-config:

    ssh_keys:
      rsa_private: |
        {{ rsa_private.key }}
      rsa_public: "{{ rsa_public.key }}"

    users:
      - default

      - name: ubuntu
        sudo: 'ALL=(ALL) NOPASSWD:ALL'
        ssh-authorized-keys:
          - "{{ rsa_public.key }}"
          - "{{ rsa_public.local }}"

    disable_root: false
    ssh_pwauth: false

---

locationId: "{{ parameter.locationId }}"

blueprints:

  - stackstorm:

      domain:
        name: "{{ parameter.domainName }}"
        service: essentials
        ipv4: auto

      ethernet:
        name: "{{ parameter.networkName }}"
        subnet: 192.168.20.0

      nodes:

        - "{{ parameter.nodeName }}":

            description: "#stackstorm #ubuntu"

            information:
              - "open a browser at https://{{ node.public }}/ to view it live"

            appliance: 'Ubuntu 14'
            cpu: 4
            memory: 8

            disks:
              - 1 50 standard

            monitoring: essentials

            glue:
              - internet 22 80 443

            cloud-config:

              packages:
                - ntp

              runcmd:

                - echo "===== Growing LVM with added disk"
                - pvcreate /dev/sdb
                - vgextend rootvol00 /dev/sdb
                - lvextend -l +100%FREE /dev/mapper/rootvol00-rootlvol00
                - resize2fs /dev/mapper/rootvol00-rootlvol00

                - echo "===== Handling ubuntu identity"
                - cp -n /etc/ssh/ssh_host_rsa_key /home/ubuntu/.ssh/id_rsa
                - cp -n /etc/ssh/ssh_host_rsa_key.pub /home/ubuntu/.ssh/id_rsa.pub
                - chown ubuntu:ubuntu /home/ubuntu/.ssh/*
                - sed -i "/StrictHostKeyChecking/s/^.*$/    StrictHostKeyChecking no/" /etc/ssh/ssh_config

                - echo "===== Installing Stackstorm"
                - curl -sSL https://raw.githubusercontent.com/DimensionDataCBUSydney/st2_dimensiondata/master/install-au.sh | sh
